name: Update README with Recent Activity

on:
  schedule:
    - cron: '*/60 * * * *' # updates every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@v0.3.0
        with:
          GH_USERNAME: adii4040   # ðŸ‘ˆ your GitHub username here
          COMMIT_MSG: "Updated README with recent GitHub activity"
